# Generated by Django 2.0.5 on 2019-03-07 20:30

from django.db import migrations, models
import django.db.models.deletion
import SB.models


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0025_queue_dedicated_time'),
    ]

    operations = [

    ]
