# Generated by Django 2.2.13 on 2020-10-29 22:34

from django.db import migrations


def forwards_func(apps, schema_editor):
    EmailTemplate = apps.get_model("SB", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    EmailTemplate.objects.using(db_alias).create(
        # id=EmailTemplate.objects.order_by('-id').first().id + 1,  # because PG sequences are not reset
        template_name='merged',
        subject='(Merged)',
        heading='Ticket merged',
        html="""<p style="font-family: sans-serif; font-size: 1em;">Hello,</p>
<p style="font-family: sans-serif; font-size: 1em;">This is a courtesy e-mail to let you know that ticket <b>{{ ticket.ticket }}</b> (<em>{{ ticket.title }}</em>) by {{ ticket.submitter_email }} has been merged to ticket <a href="{{ ticket.merged_to.staff_url }}">{{ ticket.merged_to.ticket }}</a>.</p>
<p style="font-family: sans-serif; font-size: 1em;">From now on, please answer on this ticket, or you can include the tag <b>{{ ticket.merged_to.ticket }}</b> in your e-mail subject.</p>""",
        locale='en'
    )


def reverse_func(apps, schema_editor):
    EmailTemplate = apps.get_model("SB", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    EmailTemplate.objects.using(db_alias).filter(template_name='merged').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0033_ticket_merged_to'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
