# Generated by Django 3.2.7 on 2021-09-07 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0035_alter_email_on_ticket_change'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ('template_name', 'locale'), 'verbose_name': 'e-mail template', 'verbose_name_plural': 'e-mail templates'},
        ),
        migrations.AlterField(
            model_name='kbitem',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SB.kbitem', verbose_name='SB.KBItem'),
        ),
    ]
